CREATE TABLE media_company_role(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_id BIGINT REFERENCES media (id) NOT NULL,
    company_id BIGINT REFERENCES companies (id) NOT NULL,
    role_id BIGINT REFERENCES roles (id) NOT NULL
)