CREATE TYPE date_precision AS ENUM ('DAY', 'MONTH', 'YEAR');

CREATE TABLE media_user(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_id BIGINT REFERENCES media (id) NOT NULL,
    user_id BIGINT REFERENCES users (id) NOT NULL,
    status_id BIGINT REFERENCES statuses (id) NOT NULL,
    rating SMALLINT,
    first_event_date DATE,
    last_event_date DATE,
    history_count INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    UNIQUE (media_id, user_id)
);

CREATE TABLE media_user_history(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_user_id BIGINT REFERENCES media_user (id) ON DELETE CASCADE NOT NULL,
    event_date DATE NOT NULL,
    precision date_precision NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
