CREATE TABLE IF NOT EXISTS media_external (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(255) NOT NULL,
    external_id VARCHAR(64) NOT NULL,
    media_id BIGINT REFERENCES media (id) ON DELETE CASCADE NOT NULL,
    last_synced_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_media_external_provider_external_id
    ON media_external(provider, external_id);

CREATE INDEX IF NOT EXISTS ix_media_external_media_id
    ON media_external(media_id);